import "../styles/globals.css";
import "../styles/grid_layout.css";
import Head from "next/head";
import AppProvider, { AppContext } from "../context/AppProvider";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import MusicPlayer from "../components/MusicPlayer";

function MyApp({ Component, pageProps }) {
  return (
    <AppProvider>
      <Head>
        <title>Music Power | Năng lượng ngày mới</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="icon"
          href="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/ae/1c/e2/ae1ce207-2e93-9520-f71d-2d25ea8ab274/Icon-0-0-1x_U007emarketing-0-0-0-6-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/230x0w.webp"
        />
      </Head>
      <body>
        <div className="grid wide" hidden>
          <div className="row">
            <Sidebar />
            <div className="col l-10 m-9 c-12">
              <div className="main">
                <div className="row">
                  <div className="col l-12 m-12 c-12">
                    <Header />
                  </div>
                </div>
                <Component {...pageProps} />
              </div>
            </div>
          </div>
        </div>
        <MusicPlayer />
      </body>
    </AppProvider>
  );
}

export default MyApp;
